---
abstract: 'RPC queues via RabbitMQ'
author:
  - 'Alex Vandiver C<< <alexmv@bestpractical.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: AnyEvent::RabbitMQ::RPC
name: AnyEvent-RabbitMQ-RPC
no_index:
  directory:
    - inc
requires:
  AnyEvent::RabbitMQ: 0
  Try::Tiny: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.5
